### PR TITLE
update snapshots for cohen's d changes

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
@mattansb Did something change in `effectsize`?  

I am seeing minor changes to Cohen's _d_ but I can't seem to trace it to any changes in the `NEWS` file.

### CODE REVIEW

**Comment by mattansb** [comment]
Where are the tests that have changed?

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/report/blob/master/tests/testthat/test-report.htest-t-test.R

**Comment by IndrajeetPatil** [comment]
These lines:

```r
  x <- c(1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
  y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

  set.seed(123)
  expect_snapshot(report(t.test(x, y, paired = TRUE, data = mtcars)))

  set.seed(123)
  expect_snapshot(report(t.test(x, y, paired = TRUE, data = mtcars, alternative = "l")))

  set.seed(123)
  expect_snapshot(report(t.test(x, y, paired = TRUE, data = mtcars, alternative = "g")))
```

**Comment by IndrajeetPatil** [comment]
_d_ changed from 1.07 to 1.01.

**Comment by IndrajeetPatil** [comment]
Hmm, turns out this change is observed only on macOS. Because the Windows tests are expecting 1.01.

**Comment by IndrajeetPatil** [comment]
Never mind. The tests are passing in the master without this change, so this is something local to me.
I am not sure where it's coming from, though.

**Pull request closed without merging**
