### PR TITLE
report_sample: add effective n (closes #306)

### LINKED ISSUE #306: Effective sample size per row, not total sample size in report_sample
Instead of adding a total N on top of the table, add a column at the end (after total, or as part of total) reporting the effective n for each row. If there is missing data, it is good to see how many observations underlie the means in the table.

### PR DESCRIPTION
**Pull request by rempsyc**
Closes #306

---

``` r
devtools::load_all("D:/github/forks/report")
#> ℹ Loading report

report_sample(airquality, n = TRUE)
#> # Descriptive Statistics
#> 
#> Variable             |             Summary
#> ------------------------------------------
#> Mean Ozone (SD), n   |  42.13 (32.99), 116
#> Mean Solar.R (SD), n | 185.93 (90.06), 146
#> Mean Wind (SD), n    |    9.96 (3.52), 153
#> Mean Temp (SD), n    |   77.88 (9.47), 153
#> Mean Month (SD), n   |    6.99 (1.42), 153
#> Mean Day (SD), n     |   15.80 (8.86), 153

report_sample(airquality, group_by = "Month", n = TRUE)
#> # Descriptive Statistics
#> 
#> Variable             |            5 (n=31) |           6 (n=30) |           7 (n=31) |           8 (n=31) |           9 (n=30) |       Total (n=153)
#> ----------------------------------------------------------------------------------------------------------------------------------------------------
#> Mean Ozone (SD), n   |   23.62 (22.22), 26 |   29.44 (18.21), 9 |  59.12 (31.64), 26 |  59.96 (39.68), 26 |  31.45 (24.14), 29 |  42.13 (32.99), 116
#> Mean Solar.R (SD), n | 181.30 (115.08), 27 | 190.17 (92.88), 30 | 216.48 (80.57), 31 | 171.86 (76.83), 28 | 167.43 (79.12), 30 | 185.93 (90.06), 146
#> Mean Wind (SD), n    |    11.62 (3.53), 31 |   10.27 (3.77), 30 |    8.94 (3.04), 31 |    8.79 (3.23), 31 |   10.18 (3.46), 30 |    9.96 (3.52), 153
#> Mean Temp (SD), n    |    65.55 (6.85), 31 |   79.10 (6.60), 30 |   83.90 (4.32), 31 |   83.97 (6.59), 31 |   76.90 (8.36), 30 |   77.88 (9.47), 153
#> Mean Day (SD), n     |    16.00 (9.09), 31 |   15.50 (8.80), 30 |   16.00 (9.09), 31 |   16.00 (9.09), 31 |   15.50 (8.80), 30 |   15.80 (8.86), 153
```

_Note_: Failing tests appear unrelated to the current PR.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Nice work, @rempsyc! Thanks.

Wouldn't it be better if we default to `n = TRUE`?

**Comment by rempsyc** [comment]
Thanks! I wasn't sure if we should set it as default or not since in many data sets there is no missing data at all so that information will be very redundant, and it makes the table larger and slightly less readable. I can change it if you still think it should be default, WDYT?

Also I couldn't find any tests for this function... I'm going to write some then.

**Comment by IndrajeetPatil** [comment]
Ah, yes, that's a good point. Okay, let's stick to `n = FALSE` then.

And, yes, please feel free to add some snapshot tests for this function.

**Comment by rempsyc** [comment]
Added snapshot tests; all tests for `report_sample` pass. However, I have commented tests for the `weights` argument as I don't understand what I need to pass it. It says a character vector indicating the name of a potential weigth-variable, but my attempts so far were not successful, as I am not familiar with weighting procedures generally.

**Pull request merged**
