### PR TITLE
Add support for friedman test

### PR DESCRIPTION
**Pull request by rempsyc**
addresses #309 part 2 (friedman test)

---

This fixes `report(chisq.test)` and `report(friedman.test)`, which were both broken.

``` r
library(report)
library(effectsize)
packageVersion("report")
#> [1] '0.5.7.11'

m <- as.table(rbind(c(762, 327, 468), c(484, 239, 477)))
dimnames(m) <- list(gender = c("F", "M"), party = c("Democrat", "Independent", "Republican"))
x <- chisq.test(m)

report(x)
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Pearson's Chi-squared test testing the association between gender and party
#> suggests that the effect is positive, statistically significant, and small
#> (chi2 = 30.07, p < .001; Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])
  

wb <- aggregate(warpbreaks$breaks,
                by = list(w = warpbreaks$wool,
                          t = warpbreaks$tension),
                FUN = mean)
wb
#>   w t        x
#> 1 A L 44.55556
#> 2 B L 28.22222
#> 3 A M 24.00000
#> 4 B M 28.77778
#> 5 A H 24.55556
#> 6 B H 18.77778

x <- friedman.test(wb$x, wb$w, wb$t)

report_table(x)
#> Friedman rank sum test
#> 
#> Parameter1 | Parameter2 | Chi2(1) |     p | Kendall's W |        W  CI
#> ----------------------------------------------------------------------
#> wb$x, wb$w |       wb$t |    0.33 | 0.564 |        0.11 | [0.11, 1.00]

report(x)
#> Effect sizes were labelled following Landis' (1977) recommendations.
#> 
#> The Friedman rank sum test testing the difference in ranks between wb$x, wb$w
#> and wb$t suggests that the effect is positive, statistically not significant,
#> and slight agreement (chi2 = 0.33, p = 0.564; Kendall's W = 0.11, 95% CI [0.11,
#> 1.00])
```

<sup>Created on 2023-08-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Review by strengejacke — APPROVED** [review]

**Comment by rempsyc** [comment]
Some of the tests are again failing because of a .01 difference in value in snapshots between local and GA checks... Kind of annoying having to modify them by hand to match GitHub values, maybe skipping those tests is better? What's your opinion @IndrajeetPatil ?

**Comment by IndrajeetPatil** [comment]
The difference in values comes from R-release vs R-devel? In that case, you can skip the offending case on the R-devel.

**Comment by rempsyc** [comment]
It seems that it fails even on release, check random test order, and test coverage, so not only devel...

**Comment by rempsyc** [comment]
Ok for some reasons the snapshots were not updating locally so deleted them and ran the tests again and now it seems fixed :)

**Comment by rempsyc** [comment]
There is only test coverage that is failing but I don't understand this error since it does not come up on other checks.

```
Error: Error: Failure in `C:/Users/runneradmin/AppData/Local/Temp/Rtmp06bbNH/R_LIBS88c7cc2be/report/report-tests/testthat.Rout.fail`
        │ └─base::eval(expr, envir)
 14.               │   └─base::eval(expr, envir)
 15.               └─brms::do_call(rstan::stan_model, args)
 16.                 └─brms:::eval2(call, envir = args, enclos = envir)
 17.                   └─base::eval(expr, envir, ...)
 18.                     └─base::eval(expr, envir, ...)
 19.                       └─rstan (local) .fun(model_code = .x1)
```

**Pull request merged**
