### PR TITLE
add print_html, brackets

### PR DESCRIPTION
**Pull request by strengejacke**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by strengejacke** [comment]
Failing test due to as.data.frame.lm method in parameters

**Comment by rempsyc** [comment]
In some checks, I also see this:

```
── Failure ('test-report_sample.R:39:3'): report_sample check input ────────────
`report_sample(lm(Sepal.Length ~ Species, data = iris))` did not throw the expected error.
```

Could it be tolerance since it doesn't seem to trigger on all OS?

**Comment by rempsyc** [comment]
I am getting the error locally as well. I think `report_sample` should not work on a lm object, right? So the test check is correct, but it's not producing an error when it should,

> due to as.data.frame.lm method in parameters

So what should be the fix here? I installed the latest version of `parameters` and I'm getting the same thing.

One option would be to throw an error in `report_sample` if it's not a data frame before it's passed to `parameters`?

**Comment by strengejacke** [comment]
The methods should be removed here:
https://github.com/easystats/parameters/commit/ff42d232c4d7b57a2a69b662ce03d388e8864f75

If it's not a data frame, it's tried to coerce to a data frame. That should fail for lm, unless there are more as.data.frame.lm methods in other packages

**Pull request merged**
