### PR TITLE
Remove_format_text

### PR DESCRIPTION
**Pull request by strengejacke**
removes `format_text()` where not needed. Should fix (some) test failures.

### CODE REVIEW

**Comment by strengejacke** [comment]
See #269

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by strengejacke** [comment]
I also removed _datawizard_ from being fully imported, that might cause some issues here, so waiting for check results.

**Comment by strengejacke** [comment]
@IndrajeetPatil can you check and update the snapshot tests, so we can figure out what possible remaining issues are?

**Comment by strengejacke** [comment]
There's still one failing test, I think:
https://github.com/easystats/report/runs/7896135632?check_suite_focus=true#step:6:329

**Comment by strengejacke** [comment]
I modified the tests here:
https://github.com/easystats/report/pull/272/commits/76866277b42150f838ad8d3526474f6d4e225c50

Because due to different line breaks (depending on OS?), the strings were too long to exactly appear in the output.

**Pull request merged**
