### PR TITLE
Complete Overhaul

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@strengejacke I need your advice on the weirdest thing I have seen in a while... the following function:

```r
#' Model Name Formatting
#'
#' @param model A statistical model.
#'
#' @examples
#' model <- lm(Sepal.Length ~ Species, data=iris)
#' format_model(model)
#'
#' @importFrom stringr str_detect
#' @importFrom insight model_info
#' @export
format_model <- function(model) {

  info <- insight::model_info(model)

  type <- ""

  if(info$is_bayesian){
    type <- paste0(type, "Bayesian ")
  }

  if(info$is_zeroinf){
    type <- paste0(type, "zero-inflated ")
  }
  # TODO: hurdle?

  if(info$is_logit){
    type <- paste0(type, "logistic ")
  } else if(info$is_probit){
    type <- paste0(type, "probit ")
  } else if(info$is_linear){
    type <- paste0(type, "linear ")
  } else{
    type <- paste0(type, "general linear ")
  }

  if(info$is_mixed){
    type <- paste0(type, "mixed ")
  }

  type <- paste0(type, "model")

  if(stringr::str_detect(type, "general linear")){
    type <- paste0(type,
                   " (",
                   info$family,
                   " family with a ",
                   info$link_function,
                   " link)")
  }

  return(type)
}
```

works smoothly but fails when running checks;

```
> checking examples ... ERROR
  Running examples in 'report-Ex.R' failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: format_model
  > ### Title: Model Name Formatting
  > ### Aliases: format_model
  > 
  > ### ** Examples
  > 
  > model <- lm(Sepal.Length ~ Species, data=iris)
  > format_model(model)
  Error in if (info$is_bayesian) { : argument is of length zero
  Calls: format_model
  Execution halted
```

I am unable to reproduce this error... (**`Error in if (info$is_bayesian) { : argument is of length zero`**). Have you any idea where could this issue come from?

**Comment by strengejacke** [comment]
Strange. Can you try with the latest version from insight?

**Comment by DominiqueMakowski** [comment]
Updated insight, still fails (but only when running devtools checks (and apprently on travis also)). When I run it manually everything works great 😵 🔫

**Comment by strengejacke** [comment]
No longer broken?

**Comment by DominiqueMakowski** [comment]
Still broken, just commented it all out for today (to end the day on a travis-green note 😄), will try to figure out this very bizarre error tomorrow :)

**Comment by DominiqueMakowski** [comment]
image

With the newest insight version, the error changed... but still doesn't make sense 😭 (and I still cannot manage to reproduce it manually)

**Comment by DominiqueMakowski** [comment]
For now, I hardly see removing dplyr 😅 (it is really convenient), but it could be a future milestone

**Comment by strengejacke** [comment]
> image
> 
> With the newest insight version, the error changed... but still doesn't make sense 😭 (and I still cannot manage to reproduce it manually)

It looks like lme4 is missing, can that be?

**Comment by DominiqueMakowski** [comment]
@strengejacke ok I have finished a first iteration, adapting report to the existing packages. One of the remaining things to enhance would be the table colour printing, which needs a smarter implementation (currently the width of the coloured columns is too wide due to my messy handling of the ANSI sequences).

However, while it works in local, I still have this pesky error (Ive tried on two different computers) upon devtools checks related to `insight`... could you tell me if you encounter it also?

**Comment by strengejacke** [comment]
You mean errors when checking _insight_ or errors when check _report_ relying on insight?

**Comment by DominiqueMakowski** [comment]
when checking report, but the error seems involving insight...

**Comment by strengejacke** [comment]
should work now.

**Comment by DominiqueMakowski** [comment]
Seems to work 🎉 🎊 ! Weird that it was undetectable in local. Thanks a lot!

**Comment by DominiqueMakowski** [comment]
I think the basis is here, working as expected :) Awaiting for your green light to merge.

**Comment by strengejacke** [comment]
So what's the current state of this PR and the dev-branch? Is this PR updated accordingly? Else, mabye we should merge this PR and/or the dev-branch, as things are working quite well at the moment. We can than add further refinements etc. in the dev again, or what would you say?

**Comment by DominiqueMakowski** [comment]
It's more than ok for a first basis, let's merge (and thanks a lot 😊 )

**Pull request merged**
