### PR TITLE
Separate sex and gender; report percentages for 3 categories each

### PR DESCRIPTION
**Pull request by drfeinberg**
# Description

This PR aims at updating the Sex category that previously reported only the number of female participants to deal with both Sex and Gender separately, and provide  3 options each: 
Sex: Female/Male/Other;
Gender: Woman/Man/Non-Binary

# Proposed Changes

I added new functions for gender, changed the examples to have a gender category, and a 3rd option in each example.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks a lot!

Can you please also adjust and update the tests here accordingly?
https://github.com/easystats/report/blob/master/tests/testthat/test-report_participants.R

And please also create an entry in NEWS.md to log this change.

**Comment by drfeinberg** [comment]
Hi Indrajeet,
I have made those changes.
Here is what I put in the NEWS...

* Separated sex and gender into different searches/columns
* Sex is reported % female, % male, % other, % missing if any cases are missing
* Gender is reported % Women, % Men, % Non-Binary, % missing if any cases are missing
* Age reports % missing if any cases are missing
* Tests have been updated to reflect these changes
* Tests for missing cases have also been updated to test numbers for `NA`, and strings for `""` as `""` is not NA.

It looks like there was to be a discussion about how to approach missing values in the test file.  I hope I didn't step on any toes by making some changes.  They are well commented so you can see what I did and why.
Best,
David

**Review by IndrajeetPatil — APPROVED** [review]
Thanks for the thorough treatment. 
Expect tests to fail because we still need to make some changes in `master` branch.

Once @bwiernik also approves, this can be merged.

**Comment by DominiqueMakowski** [comment]
Thanks a lot @drfeinberg !

**Comment by IndrajeetPatil** [comment]
@bwiernik Can you please have a look at this soon? Thanks.

**Comment by drfeinberg** [comment]
Hey. If it turns out my code is useful and there are other small tasks like this that need getting done, let me know, I'm happy to help out.

**Comment by bwiernik** [comment]
@IndrajeetPatil these changes look good to me. Could you update the tests?

At some point, we should generalize this by taking a named list of matching values. That would let people do their own systems and also, eg, use terms from other languages. Would also work for race/ethnicity, occupation, major, etc.

**Comment by IndrajeetPatil** [comment]
The tests to be updated are not relevant for this feature (those have already been updated in the PR itself), so I am merging this.

**Pull request merged**
