### PR TITLE
`report_effectsize`: add `type` and `rules` to chi2 objects

### PR DESCRIPTION
**Pull request by rempsyc**
Addresses #309 part 1: add `type` and `rules` to chi2 objects in `report_effectsize`.

---

``` r
library(effectsize)
devtools::load_all("C:/github/forks/report")
#> ℹ Loading report

M <- as.table(rbind(c(762, 327, 468), c(484, 239, 477)))
dimnames(M) <- list(gender = c("F", "M"), party = c("Democrat","Independent", "Republican"))
(x <- chisq.test(M)) 
#> 
#>  Pearson's Chi-squared test
#> 
#> data:  M
#> X-squared = 30.07, df = 2, p-value = 2.954e-07

report_effectsize(x)
#> Effect sizes were labelled following Funder's (2019) recommendations. 
#> 
#> small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

# Rules
report_effectsize(x, rules = "funder2019")
#> Effect sizes were labelled following Funder's (2019) recommendations. 
#> 
#> small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, rules = "gignac2016")
#> Effect sizes were labelled following Gignac's (2016) recommendations. 
#> 
#> small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, rules = "cohen1988")
#> Effect sizes were labelled following Cohen's (1988) recommendations. 
#> 
#> small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, rules = "evans1996")
#> Effect sizes were labelled following Evans's (1996) recommendations. 
#> 
#> very weak (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, rules = "lovakov2021")
#> Effect sizes were labelled following Lovakov's (2021) recommendations. 
#> 
#> very small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

# Types
report_effectsize(x, type = "cramers_v")
#> Effect sizes were labelled following Funder's (2019) recommendations. 
#> 
#> small (Adjusted Cramer's v = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, type = "pearsons_c")
#> Effect sizes were labelled following Funder's (2019) recommendations. 
#> 
#> small (Pearson's c = 0.10, 95% CI [0.07, 1.00])

report_effectsize(x, type = "tschuprows_t")
#>  
#> 
#>  (Tschuprow's t = 0.09, 95% CI [0.06, 1.00])

# tschuprows_t has no interpretation in effectsize
y <- effectsize::effectsize(x, type = "tschuprows_t")
y <- effectsize::interpret(y, rules = "funder2019")
y$Interpretation
#> NULL
names(y)
#> [1] "Tschuprows_t" "CI"           "CI_low"       "CI_high"

# max_possible not found for cohens_w
report_effectsize(x, type = "cohens_w")
#> Error in f(chisq = .chisq(Obs, Exp), n = sum(Obs), nrow = nr, ncol = nc, : object 'max_possible' not found
# Comes from effectsize
effectsize::effectsize(x, type = "cohens_w")
#> Error in f(chisq = .chisq(Obs, Exp), n = sum(Obs), nrow = nr, ncol = nc, : object 'max_possible' not found

# Change dataset for "Error: Phi is not appropriate for non-2x2 tables."
data("RCT_table")
(x <- chisq.test(RCT_table)) 
#> 
#>  Pearson's Chi-squared test with Yates' continuity correction
#> 
#> data:  RCT_table
#> X-squared = 31.566, df = 1, p-value = 1.928e-08

report_effectsize(x, type = "phi")
#> Effect sizes were labelled following Funder's (2019) recommendations. 
#> 
#> large (Adjusted's Phi = 0.36, 95% CI [0.25, 1.00])
report_effectsize(x, type = "cohens_h", rules = "sawilowsky2009")
#> Effect sizes were labelled following Savilowsky's (2009) recommendations. 
#> 
#> medium (Cohen's h = 0.74, 95% CI [0.50, 0.99])
report_effectsize(x, type = "oddsratio", rules = "chen2010")
#> Effect sizes were labelled following Chen's (2010) recommendations. 
#> 
#> medium (Odds ratio = 4.73, 95% CI [2.74, 8.17])

report_effectsize(x, type = "riskratio")
#>  
#> 
#>  (Risk_ratio = 2.54, 95% CI [1.87, 3.45])

# riskratio has no interpretation in effectsize
y <- effectsize::effectsize(x, type = "riskratio")
y <- effectsize::interpret(y, rules = "chen2010")
y$Interpretation
#> NULL
names(y)
#> [1] "Risk_ratio" "CI"         "CI_low"     "CI_high"
```

<sup>Created on 2022-12-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by rempsyc** [comment]
Added some tests. I fixed a bunch of failing snapshots on windows in #310 so I will wait for that one to be merged first before addressing the rest here.

However, I didn't accept the new `ivreg` snapshots in #310 because they provided warnings which I did not understand so I wasn't sure if it was expected or not.

**Comment by IndrajeetPatil** [comment]
What's going on here? Why is "Effect sizes were labelled ..." missing?

```r
report_effectsize(x, type = "tschuprows_t")
#>  
#> 
#>  (Tschuprow's t = 0.09, 95% CI [0.06, 1.00])
```

Is this a bug in effectsize? If yes, have you created an issue to track it?

```r
# max_possible not found for cohens_w
report_effectsize(x, type = "cohens_w")
#> Error in f(chisq = .chisq(Obs, Exp), n = sum(Obs), nrow = nr, ncol = nc, : object 'max_possible' not found
# Comes from effectsize
effectsize::effectsize(x, type = "cohens_w")
#> Error in f(chisq = .chisq(Obs, Exp), n = sum(Obs), nrow = nr, ncol = nc, : object 'max_possible' not found

```

**Comment by rempsyc** [comment]
You're correct, tschuprows, cohensw, and riskratio all have problems emerging from effectsize. For the missing interpretation, I wasn't sure if there simply was no straightforward guidelines (not familiar with these effect sizes), but thanks for confirming, I'll open corresponding issues in effectsize!

**Comment by IndrajeetPatil** [comment]
@rempsyc This should be all set. Can you please generate snapshots on Windows with the latest, GitHub version of _effectsize_?

I don't have access to a Windows machine right now, so can't do so myself.

**Comment by rempsyc** [comment]
Thanks Indra. Sorry for the delay. It's done now, I generated snapshots on Windows with the latest version of _effectsize_. Should I also replace all occurrences of `variant = .Platform$OS.type` with `variant = windows` or that's not necessary?

Also, I would like to fix lints on this file since I am working on it. A lot of the lints seem to be nested ifelse. But we're not allowed to use `dplyr::case_when` or `data.table`, so what's our in-home solution again?

**Comment by IndrajeetPatil** [comment]
> Thanks Indra. Sorry for the delay. It's done now, I generated snapshots on Windows with the latest version of _effectsize_. Should I also replace all occurrences of `variant = .Platform$OS.type` with `variant = windows` or that's not necessary?

Yes, setting `variant = "windows"` would be great. 

> Also, I would like to fix lints on this file since I am working on it. A lot of the lints seem to be nested ifelse. But we're not allowed to use `dplyr::case_when` or `data.table`, so what's our in-home solution again?

You can ignore them for now. We can revisit these later. Our in-house solution would be using `switch()` or a `list` (cf. https://github.com/easystats/easystats/issues/335).

**Comment by rempsyc** [comment]
Done. I also deleted the Unix snapshots since we're only testing for Windows.

**Comment by IndrajeetPatil** [comment]
Thanks.

Can you confirm that `report_participants.md` and `report_performance.md` now live in `_snaps/windows`?

**Comment by rempsyc** [comment]
@IndrajeetPatil I confirm! They do live there.

**Review by IndrajeetPatil — APPROVED** [review]
Thanks for all your work, @rempsyc!

**Pull request merged**
