### PR TITLE
Uncomment `report_sample()` tests

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
cf. https://github.com/easystats/easystats/issues/361

### CODE REVIEW

**Comment by strengejacke** [comment]
`select` did not work when `NULL` and `weights` specified. Should be fixed now

**Comment by rempsyc** [comment]
And I suppose in the tests the weight needs to be a numeric value rather than a character vector right? Can it be any value? Not familiar with weighting procedures at all haha

**Comment by strengejacke** [comment]
No, a character vector with the name of the weighting variable in the dataset

**Comment by IndrajeetPatil** [comment]
Someone will also need to update snapshots from a Windows machine.

**Pull request merged**
