### PR TITLE
Grouped `report_participants()` does not report gender unless argument `gender` is capitalized

### LINKED ISSUE #377: Grouped `report_participants()` does not report gender unless argument `gender` is capitalized
Grouped `report_participants()` does not report gender unless argument `gender` is capitalized, due to a bug. Reprex:

``` r
library(report)

# Works when capitalized
data <- data.frame(
  "Age" = c(22, 22, 54, 54, 8, 8, 42, 42),
  "Gender" = c("N", "N", "W", "M", "M", "M", "Non-Binary", "Non-Binary"),
  "Condition" = c("A", "A", "A", "A", "B", "B", "B", "B")
)
report_participants(data, group = "Condition")
#> [1] "For the 'Condition - A' group: 4 participants (Mean age = 38.0, SD = 18.5, range: [22, 54]; Gender: 25.0% women, 
25.0% men, 50.00% non-binary) and for the 'Condition - B' group: 4 participants (Mean age = 25.0, SD = 19.6, range: [8, 42]; 
Gender: 0.0% women, 50.0% men, 50.00% non-binary)"

# Not when lowercase
data <- data.frame(
  "Age" = c(22, 22, 54, 54, 8, 8, 42, 42),
  "gender" = c("N", "N", "W", "M", "M", "M", "Non-Binary", "Non-Binary"),
  "Condition" = c("A", "A", "A", "A", "B", "B", "B", "B")
)
report_participants(data, group = "Condition")
#> [1] "For the 'Condition - A' group: 4 participants (Mean age = 38.0, SD = 18.5, range: [22, 54]) and for the 
'Condition - B' group: 4 participants (Mean age = 25.0, SD = 19.6, range: [8, 42])"
```

<sup>Created on 2023-06-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #377

### CODE REVIEW

**Review by rempsyc — APPROVED** [review]

**Comment by strengejacke** [comment]
I can't merge, commits are not signed... 🤔

**Comment by rempsyc** [comment]
I think there is just the lints. But I can take care of it this weekend if that's ok with you

**Comment by strengejacke** [comment]
Strange I cannot sqash'n'merge... ?

**Comment by rempsyc** [comment]
It is because lint workflow has to pass to allow merging

**Comment by strengejacke** [comment]
Yeah, but why?

**Comment by rempsyc** [comment]
It is to make sure that all tests pass before merging to save time/work in the future. I would prefer that we don't merge when checks don't pass.

**Comment by strengejacke** [comment]
Given the error proneness of certain tests or that error messages are hardly avoidable in certain tests, I think that's s very strict policy 😉

**Comment by rempsyc** [comment]
Fair enough. But I think the general rule should be to try to address the lints/failing errors, and request an exception if really it is a capricious situation. I'm afraid that if it is possible to skip them, we end up always skipping them even when they are avoidable. In this particular case, it was lints that I felt I could address. I also volunteer to fix the lints in all future PRs of `report` :P

**Comment by rempsyc** [comment]
I merged but we get several warnings like below in R CMD check:

```
 ── Warning ('test-report.lm.R:39:3'): report.lm - lm intercept-only ────────────
  Using `$` in model formulas can produce unexpected results. Specify your
    model using the `data` argument instead.
```

**Pull request merged**
