### PR TITLE
[Feature] report() for BayesFactor objects

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
``` r
library(report)

rez <- BayesFactor::ttestBF(iris$Sepal.Width, iris$Sepal.Length)
report_statistics(rez)
#> [1] "BF10 > 1000"
report(rez, h0="the null hypothesis", h1="the alternative")
#> [1] "There is extreme evidence in favour of the alternative over the null hypothesis (BF10 > 1000)."
```

<sup>Created on 2024-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by mattansb** [comment]
I really dislike that the default behavior of `format_bf()` is to truncate BFs like this... `format_bf(exact = TRUE)` is much better :/

``` r
library(report)

rez <- BayesFactor::ttestBF(iris$Sepal.Width, iris$Sepal.Length)
report_statistics(rez, exact = TRUE)
#> [1] "BF10 = 6.11e+107"
report(rez, exact = TRUE)
#> [1] "There is extreme evidence in favour of H1 over H0 (BF10 = 6.11e+107)."
```

Also works now (but can probably be better…)

``` r
rez <- BayesFactor::correlationBF(iris$Sepal.Width, iris$Sepal.Length, nullInterval = c(-0.1, 0.1))
report_statistics(rez, exact = TRUE)
#> Multiple `BFBayesFactor` models detected - reporting for the first
#>   numerator model.
#>   See help("get_parameters", package = "insight").
#> [1] "BF10 = 1.18"
report(rez, exact = TRUE)
#> Multiple `BFBayesFactor` models detected - reporting for the first
#>   numerator model.
#>   See help("get_parameters", package = "insight").
#> [1] "There is anecdotal evidence in favour of H1 over H0 (BF10 = 1.18)."
```

Also auto passes to bayestestR::bf_models() \|\> report() for linear models

``` r
rez <- BayesFactor::lmBF(mpg ~ hp, data = mtcars)
report(rez)
#> Bayes factors were computed with the `BayesFactor` package, using JZS priors.
#> Compared to the (Intercept only) model (the least supported model), we found
#> extreme evidence (BF = 5.70e+04) in favour of the hp model (the most supported
#> model).
```

<sup>Created on 2024-03-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
nice addition of the LM case!

> default format

We can `exact=TRUE` in the example so that people are nudged to use it?

**Comment by mattansb** [comment]
Yes please!

**Comment by rempsyc** [comment]
Thanks, but we see:

```c
── R CMD check results ───────────────────────────────────── report 0.5.8.1 ────
Duration: 3m 47.5s

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'report.BFBayesFactor'
    ‘...’ ‘table’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking for unstated dependencies in examples ... WARNING
  '::' or ':::' import not declared from: ‘BayesFactor’
  'library' or 'require' call not declared from: ‘BayesFactor’

Error in `build_reference_index()`:
! All topics must be included in reference index
✖ Missing topics: report.BFBayesFactor
ℹ Either add to _pkgdown.yml or use @keywords internal
```

**Comment by rempsyc** [comment]
- Error in `build_reference_index()` ✅
- Some files don't follow the style guide ✅
- Lints ✅

Snapshots are still failing, but I'm afraid we'll have to fix them in a different PR :/

**Comment by rempsyc** [comment]
Snapshots updated to close #422

**Comment by rempsyc** [comment]
Cannot fix this .01 snapshot value difference between local and GHA, so skipping it...

``` c
Error: Error: Snapshot of code has changed (variant 'windows'):
old vs new
  Code
    report_performance(x7)
  Output
-   The model's explanatory power is substantial (R2 = 0.83, 95% CI [0.79, 0.86],
+   The model's explanatory power is substantial (R2 = 0.83, 95% CI [0.79, 0.87],
    adj. R2 = 0.83) and the part related to the fixed effects alone (marginal R2)
    is of 0.95 (95% CI [0.93, 0.97])
```

**Review by rempsyc — APPROVED** [review]

**Pull request merged**
