### PR TITLE
Trigger reverse dependencies check for report

### PR DESCRIPTION
**Pull request by rempsyc**
Trigger reverse dependencies check for report

### CODE REVIEW

**Comment by etiennebacher** [comment]
FYI the GHA for `revdepcheck` might not work correctly. There were no revdep errors for me (https://github.com/easystats/datawizard/pull/385) but I got some when I ran it locally (and CRAN revdep checks also errored)

I'll open an issue in the workflows repo

**Comment by rempsyc** [comment]
But Indra I am getting an `rhub` error: 

```
* checking package dependencies ... ERROR
```

https://win-builder.r-project.org/2dQVAelLQ033/00check.log

So I think submitting to CRAN will do the same? Is it important to fix this before submitting?

**Comment by IndrajeetPatil** [comment]
> Description requires `insight (>= 0.19.1)`, and CRAN version is insight 0.19.1, so it should not error?

I think you can ignore winbuilder here. It takes a while for binaries to be built, and so the winbuilder machines are always lagging behind CRAN machines that process incoming submissions. 

So you can go ahead and submit. Shouldn't be a problem, I think.

**Comment by IndrajeetPatil** [comment]
> FYI the GHA for `revdepcheck` might not work correctly. There were no revdep errors for me ([easystats/datawizard#385](https://github.com/easystats/datawizard/pull/385)) but I got some when I ran it locally (and CRAN revdep checks also errored)
> 
> I'll open an issue in the workflows repo

Hmm, that's strange. Because the GHA code to run revdepcheck is literally the same one we run locally. 
Not sure why some breakages might go undetected in the GitHub version.

**Comment by rempsyc** [comment]
report 0.5.7 submitted to CRAN

**Comment by rempsyc** [comment]
> package report_0.5.7.tar.gz has been auto-processed and is pending an automated reverse dependency check. This service will typically respond to you within the next day. 
>
> Pretests results:
> Status: OK

**Pull request closed without merging**
