### PR TITLE
\162\Fix_Unstable_Group_by_Behaviour

### LINKED ISSUE #162: Unstable group_by behaviour
Hello! Thanks for the great package for reporting everything! 
I have faced a minor issue recently and hope that this summary will help to fix it. 

**`group_by()` summary statistics fails with simple penguins data**

**To Reproduce:**
```
library(palmerpenguins)
library(tidyverse)
library(report)     

palmerpenguins::penguins %>% 
  select(species, body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  group_by(species) %>%
  report()
```

results into: 

image

The same happens with:

image

**Expected behavior** as in the examples:
```
iris %>%
    dplyr::group_by(Species) %>%
    report_table()
```
image

**interestingly,** similar calls are working with `report_sample` and `report_text`

```
palmerpenguins::penguins %>% 
  select(species, body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  group_by(species) %>%
  report_sample()

palmerpenguins::penguins %>% 
  select(species, body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  group_by(species) %>%
  report_text()
```
image

**Specifications**

Package        | Version
--------------|----------
dplyr          |   1.0.5
forcats        |   0.5.1
ggplot2        |   3.3.3
palmerpenguins |   0.1.0
purrr          |   0.3.4
R              |   4.0.5
readr          |   1.4.0
report         |   0.3.0
stringr        |   1.4.0
tibble         |   3.1.0
tidyr          |   1.1.3
tidyverse      |   1.3.1

### LINKED ISSUE #246: report() %>% as.data.frame() ignores grouping factors
**Describe the bug**
group_by(factor) %>% report() returns summary statistics by grouping factor. However, when converted to a table using as.data.frame() as indicated in the documentation, only one level of the factor is printed in the table. 

**To Reproduce**
``` r
library(tidyverse)
library(report)
data = tibble(a = rnorm(100, 0, 1), b = rnorm(100, 5, 1), fact = sample(c("var1", "var2"), 100, replace = TRUE))
data%>% group_by(fact) %>% report::report()
#> Warning: Following variable(s) were not found: n_Obs

#> Warning: Following variable(s) were not found: n_Obs
#> The data contains 100 observations, grouped by fact, of the following 3 variables:
#> 
#> - var1 (n = 60):
#>   - a: n = 60, Mean = -0.03, SD = 1.17, Median = -0.07, MAD = 1.26, range: [-2.81, 2.14], Skewness = -0.29, Kurtosis = -0.35, 0 missing
#>   - b: n = 60, Mean = 4.87, SD = 0.94, Median = 4.76, MAD = 1.17, range: [3.15, 7.09], Skewness = 0.22, Kurtosis = -0.76, 0 missing
#> 
#> - var2 (n = 40):
#>   - a: n = 40, Mean = 0.05, SD = 0.87, Median = 0.05, MAD = 0.69, range: [-1.72, 1.98], Skewness = 0.11, Kurtosis = 0.15, 0 missing
#>   - b: n = 40, Mean = 5.26, SD = 0.80, Median = 5.33, MAD = 0.96, range: [3.73, 6.90], Skewness = -0.05, Kurtosis = -0.80, 0 missing
data %>% group_by(fact) %>% report::report() %>% as.data.frame()
#> Warning: Following variable(s) were not found: n_Obs

#> Warning: Following variable(s) were not found: n_Obs
#> Group | Variable | n_Obs | Mean |   SD | Median |  MAD |   Min |  Max | Skewness | Kurtosis | n_Missing
#> -------------------------------------------------------------------------------------------------------
#> var2  |        a |    40 | 0.05 | 0.87 |   0.05 | 0.69 | -1.72 | 1.98 |     0.11 |     0.15 |         0
#> var2  |        b |    40 | 5.26 | 0.80 |   5.33 | 0.96 |  3.73 | 6.90 |    -0.05 |    -0.80 |         0
```

<sup>Created on 2022-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Expected behaviour**
as.data.frame() should report summary statistics for all grouping levels. 

**Screenshots**
NA
**Specifiations (please complete the following information):**
 - report       * 0.5.1      2022-02-22 [1] CRAN (R 4.1.2)

Minor issue/bug? Thoroughly enjoying the easystats suite of packages. Keep up the great work.

### PR DESCRIPTION
**Pull request by camden-bock**
Fixes #162 and Fixes #246 

# Description

This PR fixes the bug in #162, where the first factor group of a grouped data frame is neglected in the output of report_table.

# Proposed Changes

I added a conditional in the `report_table.grouped_df` that only uses the `merge` function when merging into a non-empty dataframe.

## Details

When I add  `print(table)` inside the for loop of  `report_table.grouped_df` of `report.data.frame` line 390 and provide `iris %>% group_by(Species)`

I get:

```r
[1] Variable  Mean      SD        Min       Max       n_Missing Group    
<0 rows> (or 0-length row.names)
      Variable  Mean        SD Min Max n_Missing      Group
1 Sepal.Length 5.936 0.5161711 4.9 7.0         0 versicolor
2  Sepal.Width 2.770 0.3137983 2.0 3.4         0 versicolor
3 Petal.Length 4.260 0.4699110 3.0 5.1         0 versicolor
4  Petal.Width 1.326 0.1977527 1.0 1.8         0 versicolor
      Variable  Mean        SD Min Max n_Missing      Group
1 Sepal.Length 5.936 0.5161711 4.9 7.0         0 versicolor
2  Sepal.Width 2.770 0.3137983 2.0 3.4         0 versicolor
3 Petal.Length 4.260 0.4699110 3.0 5.1         0 versicolor
4  Petal.Width 1.326 0.1977527 1.0 1.8         0 versicolor
5 Sepal.Length 6.588 0.6358796 4.9 7.9         0  virginica
6  Sepal.Width 2.974 0.3224966 2.2 3.8         0  virginica
7 Petal.Length 5.552 0.5518947 4.5 6.9         0  virginica
8  Petal.Width 2.026 0.2746501 1.4 2.5         0  virginica
```

Showing a zero-length table on the first iteration, and loosing that group from the output

```r
Group      |     Variable | n_Obs | Mean |   SD | Median |  MAD |  Min |  Max | Skewness | Kurtosis | n_Missing
---------------------------------------------------------------------------------------------------------------
versicolor | Sepal.Length |    50 | 5.94 | 0.52 |   5.90 | 0.52 | 4.90 | 7.00 |     0.11 |    -0.53 |         0
versicolor |  Sepal.Width |    50 | 2.77 | 0.31 |   2.80 | 0.30 | 2.00 | 3.40 |    -0.36 |    -0.37 |         0
versicolor | Petal.Length |    50 | 4.26 | 0.47 |   4.35 | 0.52 | 3.00 | 5.10 |    -0.61 |     0.05 |         0
versicolor |  Petal.Width |    50 | 1.33 | 0.20 |   1.30 | 0.22 | 1.00 | 1.80 |    -0.03 |    -0.41 |         0
virginica  | Sepal.Length |    50 | 6.59 | 0.64 |   6.50 | 0.59 | 4.90 | 7.90 |     0.12 |     0.03 |         0
virginica  |  Sepal.Width |    50 | 2.97 | 0.32 |   3.00 | 0.30 | 2.20 | 3.80 |     0.37 |     0.71 |         0
virginica  | Petal.Length |    50 | 5.55 | 0.55 |   5.55 | 0.67 | 4.50 | 6.90 |     0.55 |    -0.15 |         0
virginica  |  Petal.Width |    50 | 2.03 | 0.27 |   2.00 | 0.30 | 1.40 | 2.50 |    -0.13 |    -0.60 |         0
```

If I instead run `print(current_table)`, I find three tables as expected

```r
Variable     | Mean |   SD |  Min |  Max | n_Missing |  Group
-------------------------------------------------------------
Sepal.Length | 5.01 | 0.35 | 4.30 | 5.80 |         0 | setosa
Sepal.Width  | 3.43 | 0.38 | 2.30 | 4.40 |         0 | setosa
Petal.Length | 1.46 | 0.17 | 1.00 | 1.90 |         0 | setosa
Petal.Width  | 0.25 | 0.11 | 0.10 | 0.60 |         0 | setosa
Variable     | Mean |   SD |  Min |  Max | n_Missing |      Group
-----------------------------------------------------------------
Sepal.Length | 5.94 | 0.52 | 4.90 | 7.00 |         0 | versicolor
Sepal.Width  | 2.77 | 0.31 | 2.00 | 3.40 |         0 | versicolor
Petal.Length | 4.26 | 0.47 | 3.00 | 5.10 |         0 | versicolor
Petal.Width  | 1.33 | 0.20 | 1.00 | 1.80 |         0 | versicolor
Variable     | Mean |   SD |  Min |  Max | n_Missing |     Group
----------------------------------------------------------------
Sepal.Length | 6.59 | 0.64 | 4.90 | 7.90 |         0 | virginica
Sepal.Width  | 2.97 | 0.32 | 2.20 | 3.80 |         0 | virginica
Petal.Length | 5.55 | 0.55 | 4.50 | 6.90 |         0 | virginica
Petal.Width  | 2.03 | 0.27 | 1.40 | 2.50 |         0 | virginica
```

but of course, the same output.

Similar problem for `table_full`

```r
 [1] Variable  n_Obs     Mean      SD        Median    MAD       Min       Max       Skewness  Kurtosis 
[11] n_Missing Group    
<0 rows> (or 0-length row.names)
      Variable n_Obs  Mean        SD Median     MAD Min Max   Skewness   Kurtosis n_Missing      Group
1 Sepal.Length    50 5.936 0.5161711   5.90 0.51891 4.9 7.0  0.1053776 -0.5330095         0 versicolor
2  Sepal.Width    50 2.770 0.3137983   2.80 0.29652 2.0 3.4 -0.3628448 -0.3662374         0 versicolor
3 Petal.Length    50 4.260 0.4699110   4.35 0.51891 3.0 5.1 -0.6065077  0.0479033         0 versicolor
4  Petal.Width    50 1.326 0.1977527   1.30 0.22239 1.0 1.8 -0.0311796 -0.4100592         0 versicolor
      Variable n_Obs  Mean        SD Median     MAD Min Max   Skewness    Kurtosis n_Missing      Group
1 Sepal.Length    50 5.936 0.5161711   5.90 0.51891 4.9 7.0  0.1053776 -0.53300954         0 versicolor
2  Sepal.Width    50 2.770 0.3137983   2.80 0.29652 2.0 3.4 -0.3628448 -0.36623736         0 versicolor
3 Petal.Length    50 4.260 0.4699110   4.35 0.51891 3.0 5.1 -0.6065077  0.04790330         0 versicolor
4  Petal.Width    50 1.326 0.1977527   1.30 0.22239 1.0 1.8 -0.0311796 -0.41005924         0 versicolor
5 Sepal.Length    50 6.588 0.6358796   6.50 0.59304 4.9 7.9  0.1180151  0.03290442         0  virginica
6  Sepal.Width    50 2.974 0.3224966   3.00 0.29652 2.2 3.8  0.3659491  0.70607051         0  virginica
7 Petal.Length    50 5.552 0.5518947   5.55 0.66717 4.5 6.9  0.5494446 -0.15377856         0  virginica
8  Petal.Width    50 2.026 0.2746501   2.00 0.29652 1.4 2.5 -0.1294769 -0.60226448         0  virginica
> 
```

Two very crude modifications get the expected result. I'm not sure if there is a better way to handle `merge` in this case. 

I wonder if merge does not include new rows but adopts new columns when a non-empty data frame merges with an empty data frame?

```r
    if(!length(table_full) == 0){
      table_full <- merge(table_full, current_table_full, all = TRUE, sort = FALSE)
    }else{
      table_full <- current_table_full
    }
 ```
```r
    if(!length(table) == 0){
      table <- merge(table, current_table, all = TRUE, sort = FALSE)
    }else{
      table <- current_table
    }
```
 
 Produces table_full:
 ```r
 Variable     | n_Obs | Mean |   SD | Median |  MAD |  Min |  Max | Skewness | Kurtosis | n_Missing |  Group
-----------------------------------------------------------------------------------------------------------
Sepal.Length |    50 | 5.01 | 0.35 |   5.00 | 0.30 | 4.30 | 5.80 |     0.12 |    -0.25 |         0 | setosa
Sepal.Width  |    50 | 3.43 | 0.38 |   3.40 | 0.37 | 2.30 | 4.40 |     0.04 |     0.95 |         0 | setosa
Petal.Length |    50 | 1.46 | 0.17 |   1.50 | 0.15 | 1.00 | 1.90 |     0.11 |     1.02 |         0 | setosa
Petal.Width  |    50 | 0.25 | 0.11 |   0.20 | 0.00 | 0.10 | 0.60 |     1.25 |     1.72 |         0 | setosa
      Variable n_Obs  Mean        SD Median     MAD Min Max    Skewness   Kurtosis n_Missing      Group
1 Sepal.Length    50 5.006 0.3524897   5.00 0.29652 4.3 5.8  0.12008699 -0.2526888         0     setosa
2  Sepal.Width    50 3.428 0.3790644   3.40 0.37065 2.3 4.4  0.04116652  0.9547033         0     setosa
3 Petal.Length    50 1.462 0.1736640   1.50 0.14826 1.0 1.9  0.10639390  1.0215761         0     setosa
4  Petal.Width    50 0.246 0.1053856   0.20 0.00000 0.1 0.6  1.25386137  1.7191302         0     setosa
5 Sepal.Length    50 5.936 0.5161711   5.90 0.51891 4.9 7.0  0.10537762 -0.5330095         0 versicolor
6  Sepal.Width    50 2.770 0.3137983   2.80 0.29652 2.0 3.4 -0.36284484 -0.3662374         0 versicolor
7 Petal.Length    50 4.260 0.4699110   4.35 0.51891 3.0 5.1 -0.60650769  0.0479033         0 versicolor
8  Petal.Width    50 1.326 0.1977527   1.30 0.22239 1.0 1.8 -0.03117960 -0.4100592         0 versicolor
       Variable n_Obs  Mean        SD Median     MAD Min Max    Skewness    Kurtosis n_Missing      Group
1  Sepal.Length    50 5.006 0.3524897   5.00 0.29652 4.3 5.8  0.12008699 -0.25268880         0     setosa
2   Sepal.Width    50 3.428 0.3790644   3.40 0.37065 2.3 4.4  0.04116652  0.95470326         0     setosa
3  Petal.Length    50 1.462 0.1736640   1.50 0.14826 1.0 1.9  0.10639390  1.02157611         0     setosa
4   Petal.Width    50 0.246 0.1053856   0.20 0.00000 0.1 0.6  1.25386137  1.71913025         0     setosa
5  Sepal.Length    50 5.936 0.5161711   5.90 0.51891 4.9 7.0  0.10537762 -0.53300954         0 versicolor
6   Sepal.Width    50 2.770 0.3137983   2.80 0.29652 2.0 3.4 -0.36284484 -0.36623736         0 versicolor
7  Petal.Length    50 4.260 0.4699110   4.35 0.51891 3.0 5.1 -0.60650769  0.04790330         0 versicolor
8   Petal.Width    50 1.326 0.1977527   1.30 0.22239 1.0 1.8 -0.03117960 -0.41005924         0 versicolor
9  Sepal.Length    50 6.588 0.6358796   6.50 0.59304 4.9 7.9  0.11801512  0.03290442         0  virginica
10  Sepal.Width    50 2.974 0.3224966   3.00 0.29652 2.2 3.8  0.36594907  0.70607051         0  virginica
11 Petal.Length    50 5.552 0.5518947   5.55 0.66717 4.5 6.9  0.54944459 -0.15377856         0  virginica
12  Petal.Width    50 2.026 0.2746501   2.00 0.29652 1.4 2.5 -0.12947693 -0.60226448         0  virginica
 ```

and 

```r
Variable     | Mean |   SD |  Min |  Max | n_Missing |  Group
-------------------------------------------------------------
Sepal.Length | 5.01 | 0.35 | 4.30 | 5.80 |         0 | setosa
Sepal.Width  | 3.43 | 0.38 | 2.30 | 4.40 |         0 | setosa
Petal.Length | 1.46 | 0.17 | 1.00 | 1.90 |         0 | setosa
Petal.Width  | 0.25 | 0.11 | 0.10 | 0.60 |         0 | setosa
      Variable  Mean        SD Min Max n_Missing      Group
1 Sepal.Length 5.006 0.3524897 4.3 5.8         0     setosa
2  Sepal.Width 3.428 0.3790644 2.3 4.4         0     setosa
3 Petal.Length 1.462 0.1736640 1.0 1.9         0     setosa
4  Petal.Width 0.246 0.1053856 0.1 0.6         0     setosa
5 Sepal.Length 5.936 0.5161711 4.9 7.0         0 versicolor
6  Sepal.Width 2.770 0.3137983 2.0 3.4         0 versicolor
7 Petal.Length 4.260 0.4699110 3.0 5.1         0 versicolor
8  Petal.Width 1.326 0.1977527 1.0 1.8         0 versicolor
       Variable  Mean        SD Min Max n_Missing      Group
1  Sepal.Length 5.006 0.3524897 4.3 5.8         0     setosa
2   Sepal.Width 3.428 0.3790644 2.3 4.4         0     setosa
3  Petal.Length 1.462 0.1736640 1.0 1.9         0     setosa
4   Petal.Width 0.246 0.1053856 0.1 0.6         0     setosa
5  Sepal.Length 5.936 0.5161711 4.9 7.0         0 versicolor
6   Sepal.Width 2.770 0.3137983 2.0 3.4         0 versicolor
7  Petal.Length 4.260 0.4699110 3.0 5.1         0 versicolor
8   Petal.Width 1.326 0.1977527 1.0 1.8         0 versicolor
9  Sepal.Length 6.588 0.6358796 4.9 7.9         0  virginica
10  Sepal.Width 2.974 0.3224966 2.2 3.8         0  virginica
11 Petal.Length 5.552 0.5518947 4.5 6.9         0  virginica
12  Petal.Width 2.026 0.2746501 1.4 2.5         0  virginica
```

With resulting output as expected

```r
Group      |     Variable | n_Obs | Mean |   SD | Median |  MAD |  Min |  Max | Skewness | Kurtosis | n_Missing
---------------------------------------------------------------------------------------------------------------
setosa     | Sepal.Length |    50 | 5.01 | 0.35 |   5.00 | 0.30 | 4.30 | 5.80 |     0.12 |    -0.25 |         0
setosa     |  Sepal.Width |    50 | 3.43 | 0.38 |   3.40 | 0.37 | 2.30 | 4.40 |     0.04 |     0.95 |         0
setosa     | Petal.Length |    50 | 1.46 | 0.17 |   1.50 | 0.15 | 1.00 | 1.90 |     0.11 |     1.02 |         0
setosa     |  Petal.Width |    50 | 0.25 | 0.11 |   0.20 | 0.00 | 0.10 | 0.60 |     1.25 |     1.72 |         0
versicolor | Sepal.Length |    50 | 5.94 | 0.52 |   5.90 | 0.52 | 4.90 | 7.00 |     0.11 |    -0.53 |         0
versicolor |  Sepal.Width |    50 | 2.77 | 0.31 |   2.80 | 0.30 | 2.00 | 3.40 |    -0.36 |    -0.37 |         0
versicolor | Petal.Length |    50 | 4.26 | 0.47 |   4.35 | 0.52 | 3.00 | 5.10 |    -0.61 |     0.05 |         0
versicolor |  Petal.Width |    50 | 1.33 | 0.20 |   1.30 | 0.22 | 1.00 | 1.80 |    -0.03 |    -0.41 |         0
virginica  | Sepal.Length |    50 | 6.59 | 0.64 |   6.50 | 0.59 | 4.90 | 7.90 |     0.12 |     0.03 |         0
virginica  |  Sepal.Width |    50 | 2.97 | 0.32 |   3.00 | 0.30 | 2.20 | 3.80 |     0.37 |     0.71 |         0
virginica  | Petal.Length |    50 | 5.55 | 0.55 |   5.55 | 0.67 | 4.50 | 6.90 |     0.55 |    -0.15 |         0
virginica  |  Petal.Width |    50 | 2.03 | 0.27 |   2.00 | 0.30 | 1.40 | 2.50 |    -0.13 |    -0.60 |         0
```

### CODE REVIEW

**Comment by rempsyc** [comment]
@camden-bock I'm sorry I'm just seeing this now. Can you check if #368 addresses the same issue?

**Comment by camden-bock** [comment]
> @camden-bock I'm sorry I'm just seeing this now. Can you check if #368 addresses the same issue?

From my read of #368, it is looking to address problems with reporting groups with zero rows, amoung other groups with non-zero rows. If my understanding is correct, the issue reported in #162 and #246 is not the same issue.

#162 and #246 address one group (in the examples tested, with non-zero rows), lost only in the table output (i.e., reported correctedly in the summary output).

This was [traced to a commit](https://github.com/easystats/report/issues/162#issuecomment-825554010) where `rbind` is replaced by `merge`; the bug in #162 and #246 seems to be an unexpected problem where merge fails to add rows to a dataframe with no rows in the first iteration (the first group is always lost). This pull request is a crude solution to get expected behavior, by avoiding merge in the first ieration.

**Comment by camden-bock** [comment]
Looking at the test results, it seems that on Windows

```
── Failure ('test-report.data.frame.R:62:3'): report.data.frame ────────────────
nrow(as.data.frame(r)) (`actual`) not equal to 8 (`expected`).

  `actual`: 12
`expected`:  8
```

Test here, failure in the grouped report.
```
test_that("report.data.frame", {
  skip_if_not_installed("dplyr")

  r <- report(iris)
  expect_equal(nrow(as.data.frame(r)), 7, tolerance = 0)
  expect_equal(mean(as.data.frame(r)$Median, na.rm = TRUE), 3.6125)

  r <- report(
    iris,
    levels_percentage = FALSE,
    missing_percentage = TRUE,
    median = TRUE,
    range = FALSE,
    dispersion = FALSE
  )
  expect_equal(nrow(as.data.frame(r)), 7, tolerance = 0)
  expect_equal(mean(as.data.frame(r)$n_Obs), 107, tolerance = 0.01)

  r <- report(dplyr::group_by(iris, Species))
  expect_equal(nrow(as.data.frame(r)), 8, tolerance = 0)
  expect_equal(mean(as.data.frame(r)$n_Obs), 50, tolerance = 0)

  expect_snapshot(variant = "windows", r)
})
```

Should produce the result in [example](https://github.com/easystats/report/issues/162#issue-865046481) and [this patch](https://github.com/easystats/report/issues/162#issuecomment-1516644354) with 12 rows, and not 8 - which is [unexpected behavior](https://github.com/easystats/report/issues/162#issuecomment-1516631652).

I'll add a commit to correct this test.

**Comment by camden-bock** [comment]
> * [x]  `styler::style_pkg()`: Automatic style formatting
> 
>     * [ ]  `lintr::lint_package()`: Style checks
>       Produces error, it appears that this has been depreciated? [Deprecate `unnecessary_concatenation_linter()` r-lib/lintr#1862](https://github.com/r-lib/lintr/pull/1862)
> 
> 
> ```
> Error in unnecessary_concatenation_linter(allow_single_expression = FALSE): could not find function "unnecessary_concatenation_linter"
> ```
> 
>     * [ ]  `devtools::check()`: General checks

If unnecessary_concatenation_linter is [replaced with unneeded_concatenation_linter](https://github.com/r-lib/lintr/issues/1797#issue-1476533964), the following issues point to the functions addressed in this pull request:

```
R/report.data.frame.R:382:7: style: [commented_code_linter] Commented code should be removed.
    # table_full <- rbind(table_full, current_table_full)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
R/report.data.frame.R:390:7: style: [commented_code_linter] Commented code should be removed.
    # table <- rbind(table, current_table)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

two commits added, to resolve lintr error and to fix lintr reported issues.

**Comment by camden-bock** [comment]
- [x] `styler::style_pkg()`: Automatic style formatting
  - [x] `lintr::lint_package()`: Style checks **reports `commented code should be removed`, but only for files not modified in this pull request.**
  - [ ] `devtools::check()`: General checks
  
  Devtools fails during vignettes:

  ```r
  --- re-building ‘report.Rmd’ using rmarkdown
   Quitting from lines 111-114 (report.Rmd) 
   Error: processing vignette 'report.Rmd' failed with diagnostics:
   Sorry, `model_parameters()` failed with the following
     error (possible class `lm` not supported):
   
     'is_empty_object' is not an exported object from
     'namespace:datawizard'
   --- failed re-building ‘report.Rmd’
   
   --- re-building ‘report_table.Rmd’ using rmarkdown
   Quitting from lines 122-125 (report_table.Rmd) 
   Error: processing vignette 'report_table.Rmd' failed with diagnostics:
   Sorry, `model_parameters()` failed with the following
     error (possible class `lm` not supported):
   
     'is_empty_object' is not an exported object from
     'namespace:datawizard'
   --- failed re-building ‘report_table.Rmd’
   
   SUMMARY: processing the following files failed:
     ‘report.Rmd’ ‘report_table.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
```
  
these pieces of the vignettes don't seem to be related to the changes in this pull request.

```{r}
model <- lm(wt ~ am + mpg, data = mtcars)

report(model)
```

```{r}
model <- lm(Petal.Length ~ Species * Petal.Width, data = iris)

report_table(model)
```

**Comment by camden-bock** [comment]
When attempting these outside of devtools, they seem to succeed?

```
> model <- lm(Petal.Length ~ Species*Petal.Width, data=iris)
> model

Call:
lm(formula = Petal.Length ~ Species * Petal.Width, data = iris)

Coefficients:
                  (Intercept)              Speciesversicolor  
                       1.3276                         0.4537  
             Speciesvirginica                    Petal.Width  
                       2.9131                         0.5465  
Speciesversicolor:Petal.Width   Speciesvirginica:Petal.Width  
                       1.3228                         0.1008  

> report_table(model)
Parameter                          | Coefficient |        95% CI | t(144) |      p | Std. Coef. | Std. Coef. 95% CI |    Fit
----------------------------------------------------------------------------------------------------------------------------
(Intercept)                        |        1.33 | [ 1.07, 1.59] |  10.14 | < .001 |      -1.01 |    [-1.53, -0.48] |       
Species [versicolor]               |        0.45 | [-0.28, 1.19] |   1.21 | 0.227  |       1.16 |    [ 0.63,  1.69] |       
Species [virginica]                |        2.91 | [ 2.11, 3.72] |   7.17 | < .001 |       1.72 |    [ 1.16,  2.28] |       
Petal Width                        |        0.55 | [-0.42, 1.52] |   1.12 | 0.267  |       0.24 |    [-0.18,  0.65] |       
Species [versicolor] × Petal Width |        1.32 | [ 0.23, 2.42] |   2.38 | 0.019  |       0.57 |    [ 0.10,  1.05] |       
Species [virginica] × Petal Width  |        0.10 | [-0.94, 1.14] |   0.19 | 0.848  |       0.04 |    [-0.40,  0.49] |       
                                   |             |               |        |        |            |                   |       
AIC                                |             |               |        |        |            |                   | 128.29
AICc                               |             |               |        |        |            |                   | 129.08
BIC                                |             |               |        |        |            |                   | 149.36
R2                                 |             |               |        |        |            |                   |   0.96
R2 (adj.)                          |             |               |        |        |            |                   |   0.96
Sigma                              |             |               |        |        |            |                   |   0.36
```

```r
> library(lme4)

model <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)

report(model)
Loading required package: Matrix
We fitted a linear mixed model (estimated using REML and nloptwrap optimizer)
to predict Reaction with Days (formula: Reaction ~ Days). The model included
Days as random effects (formula: ~Days | Subject). The model's total
explanatory power is substantial (conditional R2 = 0.80) and the part related
to the fixed effects alone (marginal R2) is of 0.28. The model's intercept,
corresponding to Days = 0, is at 251.41 (95% CI [237.94, 264.87], t(174) =
36.84, p < .001). Within this model:

  - The effect of Days is statistically significant and positive (beta = 10.47,
95% CI [7.42, 13.52], t(174) = 6.77, p < .001; Std. beta = 0.54, 95% CI [0.38,
0.69])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.
```

**Comment by rempsyc** [comment]
For error

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-report_performance.R:105:3'): report_performance Bayesian) ─────
Error in `eval(code, test_env)`: cannot change value of locked binding for 'stan_glmer'
```

We are getting it in two other PRs as well, I'm not too sure what causes it.

For error
```
Error in unnecessary_concatenation_linter
```
I was getting this as well, but updating to the development version of lintr fixed it for me before.

I'll try getting through the rest of your comments as soon as possible, but it might take time, there's a lot of info.

**Comment by camden-bock** [comment]
@rempsyc 

Thanks for bearing with me, much of this thread feels like me getting up to speed on r package development workflows!

If it helps, I can summarize what I found here:
 - Issue #162 and #246 document an unexpected behavior, where one level of a group is not reported, when the report outputs a table. However, report functions properly when not outputing to a table.
 - In the discussion of #162, EBukin identified the commit where this behavior started. In this commit, dataframes are merged with `merge` instead of `rbind`.
 - base R's `merge` copies columns but not rows when merging an empty (0x0) data frame with a non-empty dataframe. This happens on report_table's first iteration through the group levels. In this case, the first iteration of the loop is effectively missed. *I added a condition to check if we are misusing merge with an empty data frame, and if so directly copy the data frame instead.*
 
 ```r
 table_full <- merge(table_full, current_table_full, all = TRUE, sort = FALSE)
 
 ===>>>

 if (!length(table_full) == 0) {
      table_full <- merge(table_full, current_table_full, all = TRUE, sort = FALSE)
 } else {
      table_full <- current_table_full
 }
 ```
 
 ```r
 table <- merge(table, current_table, all = TRUE, sort = FALSE)
 
 ===>>>
 
 if (!length(table) == 0) {
      table <- merge(table, current_table, all = TRUE, sort = FALSE)
 } else {
      table <- current_table
 }
 ```
 
 - In commit [eb200ce], after the hotfix described in #162, the test for the report_table was adjusted so that the current behavior (unexpected) passes the test. *I adjusted the expected value in the test, to revert to its original value that reflects expected behavior.* The resulting dataframe should have rows by species (3 levels) and variable (4 variables), resulting in 12 rows.
 
 ```r
 r <- report(dplyr::group_by(iris, Species))
 expect_equal(nrow(as.data.frame(r)), 8, tolerance = 0)
 
 ===>>>

 r <- report(dplyr::group_by(iris, Species))
 expect_equal(nrow(as.data.frame(r)), 12, tolerance = 0)
 ```

**Comment by rempsyc** [comment]
Ok so if this fixes 162, please edit your top post to add "Fixes #162" or "Closes #162", and if after verifying it also solves 246, please add instead, "Fixes #162 and fixes #246" (unfortunately GitHub doesn't understand if you say it just once, like "Fixes #162 and #246" so you have to type it twice). This will link this PR to the issues and close them when I merge it.

**Comment by rempsyc** [comment]
And, you can also add yourself to contributors (`"ctb"`) in the DESCRIPTION file :)

**Comment by camden-bock** [comment]
@rempsyc I've updated the DESCRIPTION and changed the description to make clear that it closes two issues; also including a comment on the issue showing the output with the patch.

**Comment by camden-bock** [comment]
@rempsyc thanks for catching that, fixed now!

**Review by rempsyc — APPROVED** [review]

**Comment by rempsyc** [comment]
Alright, all tests are passing now. Thanks for your contribution @camden-bock !

**Pull request merged**
