### PR TITLE
initializing support for wilcox test; #169

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
@DominiqueMakowski  This is just to get things started. We need to work on the exact text we are using to describe the test.
The function works with both paired and unpaired rank test and also with one-sample test.

@mattansb: Currently, there is no function to interpret rank biserial correlation, right?
As a workaround, I am using the same interpretation guidelines as Pearson's _r_, but I am not sure if that's statistically kosher.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Expect/ignore failures on Windows and Ubuntu.

**Comment by IndrajeetPatil** [comment]
lmao, don't ignore all the failures. Will have a look why the tests are failing. Pretty sure it has to do with `effectsize` failing to compute effect sizes.

**Comment by mattansb** [comment]
I think that the interpretation of the r<sub>rb</sub> is the same as Pearson's r. @bwiernik might be more knowledge here?

Why would effectsize fail to compute effect sizes????

**Comment by bwiernik** [comment]
Interpretation of effect sizes is fine. 

What is our default ranges? I think we should using a .1, .2, .3 standard from any of the 30 empirical reviews that have found those quartiles

**Comment by IndrajeetPatil** [comment]
@mattansb I think it has to do with `effectsize` failing to compute effect sizes in certain environments becuase it can't find data.

``` r
# a numeric vector
m <- c(-0.952, 0.147, -1.022, -0.43, -0.62, -0.59, -0.49, -0.01)

set.seed(123)
effectsize::effectsize(wilcox.test(m))
#> r (rank biserial) |         95% CI
#> ----------------------------------
#> -0.89             | [-0.98, -0.56]

foo <- function(x) {
  effectsize::effectsize(wilcox.test(x))
}

set.seed(123)
foo(m)
#> Error in if (ncol(data) == 2) data[[2]]: missing value where TRUE/FALSE needed
```

<sup>Created on 2021-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If run the same code interactively, it doesn't error, but the results are different:

Screenshot 2021-06-12 at 09 32 00

**Comment by IndrajeetPatil** [comment]
Pretty sure this is going to trace back to https://github.com/easystats/insight/issues/276

**Comment by IndrajeetPatil** [comment]
@bwiernik 

> What is our default ranges?

These are listed here:
https://easystats.github.io/effectsize/reference/interpret_r.html#rules

**Comment by bwiernik** [comment]
Great thanks

**Comment by IndrajeetPatil** [comment]
I have no idea what's going on here.

If I run the tests in this [file](https://github.com/IndrajeetPatil/report/blob/master/tests/testthat/test-report.htest.R) using `devtools::test_active_file()`, they pass.

But if I use "Run Tests", all tests fail with `Unable to retrieve data from htest object` message from `effectsize`.

Screenshot 2021-06-12 at 16 37 55

**Comment by IndrajeetPatil** [comment]
Merging this since the function definitely works; it's just a matter of figuring out how to write tests that won't fail.

**Pull request merged**
